services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "gophkeeper"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: