// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: pkg/gophkeeper/gophkeeper.proto

package gophkeeper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BinaryType int32

const (
	BinaryType_IMAGE_FILE BinaryType = 0
	BinaryType_VIDEO_FILE BinaryType = 1
	BinaryType_TEXT_FILE  BinaryType = 2
)

// Enum value maps for BinaryType.
var (
	BinaryType_name = map[int32]string{
		0: "IMAGE_FILE",
		1: "VIDEO_FILE",
		2: "TEXT_FILE",
	}
	BinaryType_value = map[string]int32{
		"IMAGE_FILE": 0,
		"VIDEO_FILE": 1,
		"TEXT_FILE":  2,
	}
)

func (x BinaryType) Enum() *BinaryType {
	p := new(BinaryType)
	*p = x
	return p
}

func (x BinaryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BinaryType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_gophkeeper_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (BinaryType) Type() protoreflect.EnumType {
	return &file_pkg_gophkeeper_gophkeeper_proto_enumTypes[0]
}

func (x BinaryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BinaryType.Descriptor instead.
func (BinaryType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{0}
}

type Type int32

const (
	Type_AUTH_PAIR Type = 0
	Type_BINARY    Type = 1
	Type_TEXT      Type = 2
	Type_PAY_CARD  Type = 3
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "AUTH_PAIR",
		1: "BINARY",
		2: "TEXT",
		3: "PAY_CARD",
	}
	Type_value = map[string]int32{
		"AUTH_PAIR": 0,
		"BINARY":    1,
		"TEXT":      2,
		"PAY_CARD":  3,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_gophkeeper_gophkeeper_proto_enumTypes[1].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_pkg_gophkeeper_gophkeeper_proto_enumTypes[1]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{1}
}

type AuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JwtToken string `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserSecretsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserSecretsRequest) Reset() {
	*x = GetUserSecretsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSecretsRequest) ProtoMessage() {}

func (x *GetUserSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSecretsRequest.ProtoReflect.Descriptor instead.
func (*GetUserSecretsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{4}
}

type Secret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type      string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt string `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Secret) Reset() {
	*x = Secret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Secret) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Secret) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetUserSecretsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secrets []*Secret `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
}

func (x *GetUserSecretsResponse) Reset() {
	*x = GetUserSecretsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSecretsResponse) ProtoMessage() {}

func (x *GetUserSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSecretsResponse.ProtoReflect.Descriptor instead.
func (*GetUserSecretsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserSecretsResponse) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type SaveAuthPairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecretName string `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	Login      string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password   string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Metadata   string `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *SaveAuthPairRequest) Reset() {
	*x = SaveAuthPairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveAuthPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAuthPairRequest) ProtoMessage() {}

func (x *SaveAuthPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAuthPairRequest.ProtoReflect.Descriptor instead.
func (*SaveAuthPairRequest) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *SaveAuthPairRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *SaveAuthPairRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *SaveAuthPairRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SaveAuthPairRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type SaveAuthPairResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecretId int64 `protobuf:"varint,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
}

func (x *SaveAuthPairResponse) Reset() {
	*x = SaveAuthPairResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveAuthPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAuthPairResponse) ProtoMessage() {}

func (x *SaveAuthPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAuthPairResponse.ProtoReflect.Descriptor instead.
func (*SaveAuthPairResponse) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *SaveAuthPairResponse) GetSecretId() int64 {
	if x != nil {
		return x.SecretId
	}
	return 0
}

type SavePayCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SavePayCardRequest) Reset() {
	*x = SavePayCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SavePayCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePayCardRequest) ProtoMessage() {}

func (x *SavePayCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePayCardRequest.ProtoReflect.Descriptor instead.
func (*SavePayCardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{9}
}

type SavePayCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SavePayCardResponse) Reset() {
	*x = SavePayCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SavePayCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePayCardResponse) ProtoMessage() {}

func (x *SavePayCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePayCardResponse.ProtoReflect.Descriptor instead.
func (*SavePayCardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{10}
}

type BinaryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ext  string     `protobuf:"bytes,1,opt,name=ext,proto3" json:"ext,omitempty"`
	Type BinaryType `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.BinaryType" json:"type,omitempty"`
}

func (x *BinaryInfo) Reset() {
	*x = BinaryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BinaryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryInfo) ProtoMessage() {}

func (x *BinaryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryInfo.ProtoReflect.Descriptor instead.
func (*BinaryInfo) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{11}
}

func (x *BinaryInfo) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *BinaryInfo) GetType() BinaryType {
	if x != nil {
		return x.Type
	}
	return BinaryType_IMAGE_FILE
}

type SaveBinaryDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*SaveBinaryDataRequest_Info
	//	*SaveBinaryDataRequest_ChunkData
	Data isSaveBinaryDataRequest_Data `protobuf_oneof:"data"`
}

func (x *SaveBinaryDataRequest) Reset() {
	*x = SaveBinaryDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveBinaryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBinaryDataRequest) ProtoMessage() {}

func (x *SaveBinaryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBinaryDataRequest.ProtoReflect.Descriptor instead.
func (*SaveBinaryDataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{12}
}

func (m *SaveBinaryDataRequest) GetData() isSaveBinaryDataRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *SaveBinaryDataRequest) GetInfo() *BinaryInfo {
	if x, ok := x.GetData().(*SaveBinaryDataRequest_Info); ok {
		return x.Info
	}
	return nil
}

func (x *SaveBinaryDataRequest) GetChunkData() []byte {
	if x, ok := x.GetData().(*SaveBinaryDataRequest_ChunkData); ok {
		return x.ChunkData
	}
	return nil
}

type isSaveBinaryDataRequest_Data interface {
	isSaveBinaryDataRequest_Data()
}

type SaveBinaryDataRequest_Info struct {
	Info *BinaryInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type SaveBinaryDataRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*SaveBinaryDataRequest_Info) isSaveBinaryDataRequest_Data() {}

func (*SaveBinaryDataRequest_ChunkData) isSaveBinaryDataRequest_Data() {}

type SaveBinaryDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId int64 `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Size   int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *SaveBinaryDataResponse) Reset() {
	*x = SaveBinaryDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveBinaryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBinaryDataResponse) ProtoMessage() {}

func (x *SaveBinaryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBinaryDataResponse.ProtoReflect.Descriptor instead.
func (*SaveBinaryDataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{13}
}

func (x *SaveBinaryDataResponse) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *SaveBinaryDataResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SaveTextDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId int64 `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
}

func (x *SaveTextDataResponse) Reset() {
	*x = SaveTextDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveTextDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTextDataResponse) ProtoMessage() {}

func (x *SaveTextDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTextDataResponse.ProtoReflect.Descriptor instead.
func (*SaveTextDataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{14}
}

func (x *SaveTextDataResponse) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type Type  `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.Type" json:"type,omitempty"`
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteItemRequest) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_AUTH_PAIR
}

type DeleteItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{16}
}

type GetAuthPairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAuthPairRequest) Reset() {
	*x = GetAuthPairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAuthPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthPairRequest) ProtoMessage() {}

func (x *GetAuthPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthPairRequest.ProtoReflect.Descriptor instead.
func (*GetAuthPairRequest) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{17}
}

func (x *GetAuthPairRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAuthPairResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *GetAuthPairResponse) Reset() {
	*x = GetAuthPairResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAuthPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthPairResponse) ProtoMessage() {}

func (x *GetAuthPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthPairResponse.ProtoReflect.Descriptor instead.
func (*GetAuthPairResponse) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{18}
}

func (x *GetAuthPairResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetAuthPairResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetPayCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPayCardRequest) Reset() {
	*x = GetPayCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPayCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayCardRequest) ProtoMessage() {}

func (x *GetPayCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayCardRequest.ProtoReflect.Descriptor instead.
func (*GetPayCardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{19}
}

func (x *GetPayCardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPayCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPayCardResponse) Reset() {
	*x = GetPayCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPayCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayCardResponse) ProtoMessage() {}

func (x *GetPayCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayCardResponse.ProtoReflect.Descriptor instead.
func (*GetPayCardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{20}
}

type GetBinaryDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBinaryDataRequest) Reset() {
	*x = GetBinaryDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBinaryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBinaryDataRequest) ProtoMessage() {}

func (x *GetBinaryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBinaryDataRequest.ProtoReflect.Descriptor instead.
func (*GetBinaryDataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{21}
}

func (x *GetBinaryDataRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTextDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTextDataRequest) Reset() {
	*x = GetTextDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTextDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextDataRequest) ProtoMessage() {}

func (x *GetTextDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gophkeeper_gophkeeper_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextDataRequest.ProtoReflect.Descriptor instead.
func (*GetTextDataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP(), []int{22}
}

func (x *GetTextDataRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_pkg_gophkeeper_gophkeeper_proto protoreflect.FileDescriptor

var file_pkg_gophkeeper_gophkeeper_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2f, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x1a, 0x1e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a,
	0x0b, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2b,
	0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x6a, 0x77, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x43, 0x0a, 0x0f, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0x2b, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x17, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x46, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x07, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x22,
	0x83, 0x01, 0x0a, 0x13, 0x53, 0x61, 0x76, 0x65, 0x41, 0x75, 0x74, 0x68, 0x50, 0x61, 0x69, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x33, 0x0a, 0x14, 0x53, 0x61, 0x76, 0x65, 0x41, 0x75, 0x74,
	0x68, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x61,
	0x76, 0x65, 0x50, 0x61, 0x79, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x15, 0x0a, 0x13, 0x53, 0x61, 0x76, 0x65, 0x50, 0x61, 0x79, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4a, 0x0a, 0x0a, 0x42, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x65, 0x78, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x6e, 0x0a, 0x15, 0x53, 0x61, 0x76, 0x65, 0x42, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x70,
	0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0a, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00,
	0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x45, 0x0a, 0x16, 0x53, 0x61, 0x76, 0x65, 0x42, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x2f, 0x0a, 0x14, 0x53, 0x61,
	0x76, 0x65, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x11, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x47, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x50, 0x61, 0x69,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x23, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x50, 0x61, 0x79, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x61, 0x79, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x24,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x2a, 0x3b, 0x0a, 0x0a, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x5f, 0x46, 0x49, 0x4c, 0x45,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x5f, 0x46, 0x49, 0x4c, 0x45,
	0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x45, 0x58, 0x54, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10,
	0x02, 0x2a, 0x39, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x55, 0x54,
	0x48, 0x5f, 0x50, 0x41, 0x49, 0x52, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x49, 0x4e, 0x41,
	0x52, 0x59, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x02, 0x12, 0x0c,
	0x0a, 0x08, 0x50, 0x41, 0x59, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x10, 0x03, 0x32, 0xc7, 0x07, 0x0a,
	0x0a, 0x47, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x04, 0x41,
	0x75, 0x74, 0x68, 0x12, 0x17, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67,
	0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x1b, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x21, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0c, 0x53, 0x61,
	0x76, 0x65, 0x41, 0x75, 0x74, 0x68, 0x50, 0x61, 0x69, 0x72, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x70,
	0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x41, 0x75, 0x74, 0x68,
	0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x6f,
	0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x41, 0x75, 0x74,
	0x68, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a,
	0x0b, 0x53, 0x61, 0x76, 0x65, 0x50, 0x61, 0x79, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1e, 0x2e, 0x67,
	0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x50, 0x61,
	0x79, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67,
	0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x50, 0x61,
	0x79, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a,
	0x0e, 0x53, 0x61, 0x76, 0x65, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x21, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x61, 0x76,
	0x65, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e,
	0x53, 0x61, 0x76, 0x65, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x50, 0x0a, 0x0c, 0x53, 0x61, 0x76, 0x65,
	0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x20, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x4b, 0x0a, 0x0a, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x75,
	0x74, 0x68, 0x50, 0x61, 0x69, 0x72, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x50, 0x61, 0x69, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x50, 0x61, 0x69, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x61,
	0x79, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x79, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x79, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x30, 0x01, 0x12, 0x4d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x65,
	0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x30, 0x01, 0x42, 0x17, 0x5a, 0x15, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_gophkeeper_gophkeeper_proto_rawDescOnce sync.Once
	file_pkg_gophkeeper_gophkeeper_proto_rawDescData = file_pkg_gophkeeper_gophkeeper_proto_rawDesc
)

func file_pkg_gophkeeper_gophkeeper_proto_rawDescGZIP() []byte {
	file_pkg_gophkeeper_gophkeeper_proto_rawDescOnce.Do(func() {
		file_pkg_gophkeeper_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_gophkeeper_gophkeeper_proto_rawDescData)
	})
	return file_pkg_gophkeeper_gophkeeper_proto_rawDescData
}

var file_pkg_gophkeeper_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_gophkeeper_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pkg_gophkeeper_gophkeeper_proto_goTypes = []any{
	(BinaryType)(0),                // 0: gophkeeper.BinaryType
	(Type)(0),                      // 1: gophkeeper.Type
	(*AuthRequest)(nil),            // 2: gophkeeper.AuthRequest
	(*AuthResponse)(nil),           // 3: gophkeeper.AuthResponse
	(*RegisterRequest)(nil),        // 4: gophkeeper.RegisterRequest
	(*RegisterResponse)(nil),       // 5: gophkeeper.RegisterResponse
	(*GetUserSecretsRequest)(nil),  // 6: gophkeeper.GetUserSecretsRequest
	(*Secret)(nil),                 // 7: gophkeeper.Secret
	(*GetUserSecretsResponse)(nil), // 8: gophkeeper.GetUserSecretsResponse
	(*SaveAuthPairRequest)(nil),    // 9: gophkeeper.SaveAuthPairRequest
	(*SaveAuthPairResponse)(nil),   // 10: gophkeeper.SaveAuthPairResponse
	(*SavePayCardRequest)(nil),     // 11: gophkeeper.SavePayCardRequest
	(*SavePayCardResponse)(nil),    // 12: gophkeeper.SavePayCardResponse
	(*BinaryInfo)(nil),             // 13: gophkeeper.BinaryInfo
	(*SaveBinaryDataRequest)(nil),  // 14: gophkeeper.SaveBinaryDataRequest
	(*SaveBinaryDataResponse)(nil), // 15: gophkeeper.SaveBinaryDataResponse
	(*SaveTextDataResponse)(nil),   // 16: gophkeeper.SaveTextDataResponse
	(*DeleteItemRequest)(nil),      // 17: gophkeeper.DeleteItemRequest
	(*DeleteItemResponse)(nil),     // 18: gophkeeper.DeleteItemResponse
	(*GetAuthPairRequest)(nil),     // 19: gophkeeper.GetAuthPairRequest
	(*GetAuthPairResponse)(nil),    // 20: gophkeeper.GetAuthPairResponse
	(*GetPayCardRequest)(nil),      // 21: gophkeeper.GetPayCardRequest
	(*GetPayCardResponse)(nil),     // 22: gophkeeper.GetPayCardResponse
	(*GetBinaryDataRequest)(nil),   // 23: gophkeeper.GetBinaryDataRequest
	(*GetTextDataRequest)(nil),     // 24: gophkeeper.GetTextDataRequest
	(*wrapperspb.StringValue)(nil), // 25: google.protobuf.StringValue
}
var file_pkg_gophkeeper_gophkeeper_proto_depIdxs = []int32{
	7,  // 0: gophkeeper.GetUserSecretsResponse.secrets:type_name -> gophkeeper.Secret
	0,  // 1: gophkeeper.BinaryInfo.type:type_name -> gophkeeper.BinaryType
	13, // 2: gophkeeper.SaveBinaryDataRequest.info:type_name -> gophkeeper.BinaryInfo
	1,  // 3: gophkeeper.DeleteItemRequest.type:type_name -> gophkeeper.Type
	2,  // 4: gophkeeper.Gophkeeper.Auth:input_type -> gophkeeper.AuthRequest
	4,  // 5: gophkeeper.Gophkeeper.Register:input_type -> gophkeeper.RegisterRequest
	6,  // 6: gophkeeper.Gophkeeper.GetUserSecretsList:input_type -> gophkeeper.GetUserSecretsRequest
	9,  // 7: gophkeeper.Gophkeeper.SaveAuthPair:input_type -> gophkeeper.SaveAuthPairRequest
	11, // 8: gophkeeper.Gophkeeper.SavePayCard:input_type -> gophkeeper.SavePayCardRequest
	14, // 9: gophkeeper.Gophkeeper.SaveBinaryData:input_type -> gophkeeper.SaveBinaryDataRequest
	25, // 10: gophkeeper.Gophkeeper.SaveTextData:input_type -> google.protobuf.StringValue
	17, // 11: gophkeeper.Gophkeeper.DeleteItem:input_type -> gophkeeper.DeleteItemRequest
	19, // 12: gophkeeper.Gophkeeper.GetAuthPair:input_type -> gophkeeper.GetAuthPairRequest
	21, // 13: gophkeeper.Gophkeeper.GetPayCard:input_type -> gophkeeper.GetPayCardRequest
	23, // 14: gophkeeper.Gophkeeper.GetBinaryData:input_type -> gophkeeper.GetBinaryDataRequest
	24, // 15: gophkeeper.Gophkeeper.GetTextData:input_type -> gophkeeper.GetTextDataRequest
	3,  // 16: gophkeeper.Gophkeeper.Auth:output_type -> gophkeeper.AuthResponse
	5,  // 17: gophkeeper.Gophkeeper.Register:output_type -> gophkeeper.RegisterResponse
	8,  // 18: gophkeeper.Gophkeeper.GetUserSecretsList:output_type -> gophkeeper.GetUserSecretsResponse
	10, // 19: gophkeeper.Gophkeeper.SaveAuthPair:output_type -> gophkeeper.SaveAuthPairResponse
	12, // 20: gophkeeper.Gophkeeper.SavePayCard:output_type -> gophkeeper.SavePayCardResponse
	15, // 21: gophkeeper.Gophkeeper.SaveBinaryData:output_type -> gophkeeper.SaveBinaryDataResponse
	16, // 22: gophkeeper.Gophkeeper.SaveTextData:output_type -> gophkeeper.SaveTextDataResponse
	18, // 23: gophkeeper.Gophkeeper.DeleteItem:output_type -> gophkeeper.DeleteItemResponse
	20, // 24: gophkeeper.Gophkeeper.GetAuthPair:output_type -> gophkeeper.GetAuthPairResponse
	22, // 25: gophkeeper.Gophkeeper.GetPayCard:output_type -> gophkeeper.GetPayCardResponse
	25, // 26: gophkeeper.Gophkeeper.GetBinaryData:output_type -> google.protobuf.StringValue
	25, // 27: gophkeeper.Gophkeeper.GetTextData:output_type -> google.protobuf.StringValue
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_gophkeeper_gophkeeper_proto_init() }
func file_pkg_gophkeeper_gophkeeper_proto_init() {
	if File_pkg_gophkeeper_gophkeeper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserSecretsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Secret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserSecretsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SaveAuthPairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*SaveAuthPairResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SavePayCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*SavePayCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*BinaryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*SaveBinaryDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*SaveBinaryDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*SaveTextDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*GetAuthPairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*GetAuthPairResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*GetPayCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*GetPayCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*GetBinaryDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gophkeeper_gophkeeper_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*GetTextDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_gophkeeper_gophkeeper_proto_msgTypes[12].OneofWrappers = []any{
		(*SaveBinaryDataRequest_Info)(nil),
		(*SaveBinaryDataRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_gophkeeper_gophkeeper_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_gophkeeper_gophkeeper_proto_goTypes,
		DependencyIndexes: file_pkg_gophkeeper_gophkeeper_proto_depIdxs,
		EnumInfos:         file_pkg_gophkeeper_gophkeeper_proto_enumTypes,
		MessageInfos:      file_pkg_gophkeeper_gophkeeper_proto_msgTypes,
	}.Build()
	File_pkg_gophkeeper_gophkeeper_proto = out.File
	file_pkg_gophkeeper_gophkeeper_proto_rawDesc = nil
	file_pkg_gophkeeper_gophkeeper_proto_goTypes = nil
	file_pkg_gophkeeper_gophkeeper_proto_depIdxs = nil
}
